### ISSUE TITLE
Add monitoring on the proxy server 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#268]
### What
The server proxy was stopped this week-end, leading to query.openfoodfacts.org timeouting, leading to the whole website timeouting. 

```[tasklist]
### Tasks
- [ ] We should add monitoring on the proxy server.
- [ ] We should ensure that workers are freed within a reasonable amount of time (like 10s, since the answer time has been greatly reduced by openfoodfacts-query). This ensures that workers are not depleted in case openfoodfacts-query runs slow or fails alltogether
- [ ] We could even have an automatic fallback on the product opener classic tags should openfoodfacts-query fail.
```
