### ISSUE TITLE
Deployment automation (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#425]
### Deployment automation
- [ ] live connect of openfoodfacts-search to open food facts on staging
- [ ] deploy openfoodfacts-search to prod
- [ ] [deploy taxonomy editor to stagging](https://github.com/openfoodfacts/taxonomy-editor/issues/73)
- [ ] [deploy facets knowledge to stagging](https://github.com/openfoodfacts/facets-knowledge-panels/issues/34)
- [ ] [deploy openfoodfacts-events to prod](https://github.com/openfoodfacts/openfoodfacts-events/issues/151)
- [ ] OpenFoodFacts server: https://github.com/openfoodfacts/openfoodfacts-server/issues/5511

### Improve the deployment of Folksonomy Engine (tracker)
- [ ] https://github.com/openfoodfacts/folksonomy_api/issues/33
- [ ] https://github.com/openfoodfacts/folksonomy_api/issues/38
- [ ] https://github.com/openfoodfacts/folksonomy_api/issues/35

### Part of
- #88
