### ISSUE TITLE
Create & automate deployment to dev environment for Product Opener / Robotoff / Flutter app

### ISSUE THREAD

**Issue by laulowen** [openfoodfacts/openfoodfacts-infrastructure#46]
- [x] Automate the deployment of Product Opener
  - [x] https://github.com/openfoodfacts/openfoodfacts-server/pull/5436
  - [x] https://github.com/openfoodfacts/openfoodfacts-server/pull/5446
- [x] Automate the deployment of Robotoff
  - [x] https://github.com/openfoodfacts/robotoff/pull/429
  - [x] https://github.com/openfoodfacts/robotoff/pull/353
- [ ] Automate the deployment of Flutter
  - [x] Android (build deployment working)
  - [x] https://github.com/openfoodfacts/smooth-app/issues/454

**Comment by teolemon** [comment]
fixed :-)
