### ISSUE TITLE
Migrate Docker containers to off-docker QEMU machine

### ISSUE THREAD

**Issue by ocervell** [openfoodfacts/openfoodfacts-infrastructure#62]
**Goal:** Migrate Docker containers running on Proxmox VMs to new QEMU machine after .net [outage](https://docs.google.com/document/d/1mbPoKK9gBkmKXYfz2_DykFlUo5ZE-JaZgeivdH6Mmz8/edit#heading=h.33ifrwwx97d2)

**Tasks:**
- [x] QEMU VM Scripts / Commands (manual):
  - [x] Install Docker
  - [x] Switch Docker storage driver to `overlay2`, recommended for production
  - [x] Create `off` user on the VM
  - [x] Mount ZFS clones in `/mnt/products`, `/mnt_users`, `/mnt/orgs` and add to /etc/fstab
  - [x] Correct chown permissions for `/mnt/products`, `/mnt/users`, `/mnt/orgs` to `off:off`
  - [x] Add data dumps to `/mnt/data`
  - [x] Rsync `/mnt/product_images`

- [x] Docker Compose deployments (manual)
  - [x] mongo-dev
  - [x] robotoff-net
  - [x] robotoff-ann
  - [x] robotoff-ml
  - [x] off-net
  - [x] monitoring
- [x] MongoDB daily tasks (manual):
  - [x] Import production data into MongoDB (manual)
  - [x] Refresh product tags (manual)
- [x] Switch GitHub environments secrets to new host for deployments:
  - [x] openfoodfacts-server: `HOST=10.1.0.200`, `USER=off`, `SSH_PRIVATE_KEY=<off_private_key>`, `MONGODB_HOST=10.1.0.200`
  - [x] robotoff: `HOST=10.1.0.200`, `USER=off`, `SSH_PRIVATE_KEY=<off_private_key>`, `POSTGRES_HOST=10.1.0.200`, `MONGO_URI=mongodb://10.1.0.200:27017`, `INFLUXDB_HOST=10.1.0.200`, `ELASTICSEARCH_HOSTS=10.1.0.200`
  - [x] robotoff-ann: `HOST=10.1.0.200`, `USER=off`, `SSH_PRIVATE_KEY=<off_private_key>`
  - [x] impactestimator: `HOST=10.1.0.200`, `USER=off`, `SSH_PRIVATE_KEY=<off_private_key>`
  - [x] monitoring: `HOST=10.1.0.200`, `USER=off`, `SSH_PRIVATE_KEY=<off_private_key>`
- [x] Point NGINX routes to new VM Docker containers:
  - [x] `openfoodfacts.net` --> `10.1.0.200:80` # OFF
  - [x] `robotoff.openfoodfacts.net/api/v1/ann/*` --> `10.1.0.200:5501` # Robotoff ANN
  - [x] `robotoff.openfoodfacts.net/api/v1/*` --> `10.1.0.200:5500` # Robotoff
  - [x] `monitoring.openfoodfacts.net/alerts*` --> `10.1.0.200:9115` # AlertManager
  - [x] `monitoring.openfoodfacts.net/metrics*` --> `10.1.0.200:9090` # Prometheus
  - [x] `monitoring.openfoodfacts.net` --> `10.1.0.200:3000` # Grafana

- [x] PRs for automated deployments updates:
  - [x] https://github.com/openfoodfacts/openfoodfacts-server/pull/5947
  - [x] https://github.com/openfoodfacts/robotoff/pull/463
  - [x] https://github.com/openfoodfacts/robotoff-ann/pull/18
  - [x] https://github.com/openfoodfacts/impactestimator/pull/4

- [ ] Run automated deployments successfully:
  - [x] `robotoff-net`
  - [x] `robotoff-ml`
  - [ ] `robotoff-ann`
  - [x] `mongo-dev`
  - [x] `off-net`
  - [x] `monitoring`
  - [x] `impactestimator-net`

**Comment by alexgarel** [comment]
This one is all done since a long time ! Thanks again @ocervell :-)
